### ISSUE TITLE
add: config yaml instead of cli

### ISSUE THREAD

**Issue by gottaeat** [gottaeat/bands#10]
required for doing the multi-server<-multi-channel stuff.

**Comment by gottaeat** [comment]
config should be like this:
```yaml
network:
    - name: testnet
      address: irc.example.com
      port: 6697
      botname: bands_a
      tls: true
      verify_tls: false
      speed: 0
      channels:
       - #test
       - #test2
    - name: testnet2
      address: irc.example.org
      port: 6697
      botname: bands_b
      tls: true
      verify_tls: true
      speed: 1
      channels:
       - #test3
       - #test4
```

1. one openai instance for all servers
2. one connection per server
3. multiple channels per server
```
cli
|
openai
|
`- server a (socket1)
   `- channel a
   `- channel b
`- server b (socket2)
   `- channel a
   `- channel b
```

```
CLI() will parse the config and run

Core() will be split into
`- Server()  -> will open the socket
   `- has the send_* commands
   `- main while recv loop here, has to be, for pongs etc.
   `- after joining, if msg for channel -> talk to channel
`- Channel() -> will handle classes per channel name
   `- has the ?cmd handling
```
